upy_error/__init__.py,sha256=WaYzZSBulP65lT4hGgu4M00ywIavbGgKMe4zYWKkkKg,99
upy_error/base.py,sha256=R8rnNvKNXnxJmX0afxjvol7jnSA_Ji8NOvu4jyuGL0U,904
upy_error/config.py,sha256=EJfSam2GYBCYiURJl5TN0TfzoFUrhaK95xI2TGjtUoY,431
upy_error-0.0.2.dist-info/METADATA,sha256=d5c97tDLn6a9KNfUkFE2l97h5M1GQt-lHl74CN8gpB4,2277
upy_error-0.0.2.dist-info/WHEEL,sha256=z9j0xAa_JmUKMpmz72K0ZGALSM_n-wQVmGbleXx2VHg,110
upy_error-0.0.2.dist-info/top_level.txt,sha256=7kD2kweUO542m9oU_Nfje6StR7CsCcr2QAARVf_XtYY,10
upy_error-0.0.2.dist-info/RECORD,,
